### ISSUE TITLE
Is there any way to shift regions/ region poles at all? 

### ISSUE THREAD

**Issue by VeganFN** [techfortress/PopulationDensity#103]
I have a server with a massive spawn and a lot has already happened, however I would now like to add PopulationDensity, but the spawn does not lineup with the region/region poles sadly. Is there any way to change this?

**Comment by zedwick** [comment]
I'm afraid there is no way to move the region posts horizontally at all. they can only be moved vertically, as they would sit on the tallest block.

However there is the "CityRegion" which is not connected to the region post coordinates. It is intended to function as a set spawn location.

Set the city world name in your config.yml

```
  CityWorldName: world
```

Where `world` is the name of the world where your spawn is (your primary/overworld world). With this set you can use `/spawn` to teleport from any warp post back to your world spawn location. Players can also telelport from your spawn/cityregion location as if it were a region post, but the plugin will not generate a region post there automatically.
