### ISSUE TITLE
Editable Signs in 1.20

### ISSUE THREAD

**Issue by MajdT51** [techfortress/PopulationDensity#106]
Hi, I would like to report a bug after the new update to 1.20

The signs are now editable and any player can edit the signs on the region post

We are on paper 1.20.1 and using the latest version of the plugin.

<img width="534" alt="image" src="https://github.com/MLG-Fortress/PopulationDensity/assets/50261972/0327e3a0-da0f-4ac3-b954-fb2e51dad3aa">

If you point me in the right direction and tell me how to build the plugin locally with Intellij or maven then I could try to fix it. 
Thanks

**Comment by RoboMWM** [comment]
`mvn package` to build locally.

**Comment by MajdT51** [comment]
@RoboMWM are you gonna make a new release, or should i use my own jar file :)? Thanks
